timezone: America/New_York
title: Olin Design Principles
media_base_url: https://olin-design-principles.s3.amazonaws.com/
# baseurl: /odp

collections:
  pages:
    output: true
    permalink: /:path
  courses:
    title: Courses
    output: true
  instructors:
    title: Instructors
    output: true
  principles:
    title: Principles
    output: true
  sightings:
    title: Sightings
    output: true

defaults:
  - scope:
      path: ''
      type: pages
    values:
       layout: default
  - scope:
      path: ''
      type: principles
    values:
      layout: principle
  - scope:
      path: ''
      type: sightings
    values:
      body-class: sighting
      layout: sighting
  - scope:
      path: ''
      type: courses
    values:
      layout: course
  - scope:
      path: ''
      type: instructors
    values:
      layout: instructor

exclude:
  - Gemfile
  - Gemfile.lcok
  - README.md
  - lambda
  - scripts
  - TODO*

sass:
    load_paths:
        - _sass
        - node_modules
